/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import dao.CategoriaDAO;
import entidade.Categoria;
import javax.swing.JOptionPane;

/**
 *
 * @author evely
 */
public class DlgCadastro extends javax.swing.JDialog {
        int id = 0;
        Categoria categoria = new Categoria();
 
        //Categoria categ = new Categoria();
        
    public DlgCadastro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        pnllivros.setVisible(false);
        pnlclientes.setVisible(false);
        pnlautor.setVisible(false);
    }
    
    public DlgCadastro(java.awt.Frame parent, boolean modal, Categoria categoria) {
        super(parent, modal);
        initComponents();
        pnllivros.setVisible(false);
        pnlclientes.setVisible(false);
        pnlautor.setVisible(false);
        tfddescricao.setText(categoria.getDescricao());
        
        if (categoria.getSituacao() == 'a') {
            cmbSituacaocat.setSelectedIndex(0);
        } else {
            cmbSituacaocat.setSelectedIndex(1);
        }
        this.categoria = categoria;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnllivros = new javax.swing.JPanel();
        lblregistrar = new javax.swing.JLabel();
        cmbestante = new javax.swing.JComboBox<>();
        cmbidioma = new javax.swing.JComboBox<>();
        cmbcategoria = new javax.swing.JComboBox<>();
        cmbautor = new javax.swing.JComboBox<>();
        tfdtitulo = new javax.swing.JTextField();
        lblfundoLivros = new javax.swing.JLabel();
        pnlclientes = new javax.swing.JPanel();
        pnlcategoria = new javax.swing.JPanel();
        btncadastrarcat = new javax.swing.JButton();
        cmbSituacaocat = new javax.swing.JComboBox<>();
        tfddescricao = new javax.swing.JTextField();
        lblfundo = new javax.swing.JLabel();
        pnlautor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnllivros.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnllivros.add(lblregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 515, 200, 50));

        cmbestante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnllivros.add(cmbestante, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, 130, 20));

        cmbidioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnllivros.add(cmbidioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 120, 20));

        cmbcategoria.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cmbcategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnllivros.add(cmbcategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 130, 20));

        cmbautor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cmbautor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnllivros.add(cmbautor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 130, 20));

        tfdtitulo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfdtitulo.setBorder(null);
        tfdtitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdtituloActionPerformed(evt);
            }
        });
        pnllivros.add(tfdtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 157, 320, 30));
        tfdtitulo.getAccessibleContext().setAccessibleName("");

        lblfundoLivros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/livraria/imagens/cadastro livros.png"))); // NOI18N
        pnllivros.add(lblfundoLivros, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(pnllivros, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 620));

        javax.swing.GroupLayout pnlclientesLayout = new javax.swing.GroupLayout(pnlclientes);
        pnlclientes.setLayout(pnlclientesLayout);
        pnlclientesLayout.setHorizontalGroup(
            pnlclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        pnlclientesLayout.setVerticalGroup(
            pnlclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        getContentPane().add(pnlclientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 620));

        pnlcategoria.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btncadastrarcat.setBackground(new java.awt.Color(32, 171, 199));
        btncadastrarcat.setFont(new java.awt.Font("Verdana", 0, 27)); // NOI18N
        btncadastrarcat.setForeground(new java.awt.Color(255, 255, 255));
        btncadastrarcat.setText("Registrar");
        btncadastrarcat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncadastrarcatActionPerformed(evt);
            }
        });
        pnlcategoria.add(btncadastrarcat, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 360, 60));

        cmbSituacaocat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbSituacaocat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo\t", "Inativo" }));
        pnlcategoria.add(cmbSituacaocat, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 140, 30));

        tfddescricao.setBorder(null);
        pnlcategoria.add(tfddescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 430, 30));

        lblfundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/livraria/imagens/cadastro categoria.jpg"))); // NOI18N
        pnlcategoria.add(lblfundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(pnlcategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 620));

        javax.swing.GroupLayout pnlautorLayout = new javax.swing.GroupLayout(pnlautor);
        pnlautor.setLayout(pnlautorLayout);
        pnlautorLayout.setHorizontalGroup(
            pnlautorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        pnlautorLayout.setVerticalGroup(
            pnlautorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        getContentPane().add(pnlautor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btncadastrarcatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncadastrarcatActionPerformed

        CategoriaDAO categDAO = new CategoriaDAO();        
        id = categoria.getId();
        categoria.setDescricao(tfddescricao.getText());

        int indice = cmbSituacaocat.getSelectedIndex();
        if (indice == 0) {
            categoria.setSituacao('a');
        } else {
            categoria.setSituacao('i');
        }

        String retorno = null;
        
        if (id == 0) {
            retorno = categDAO.salvar(categoria);
        } else {
            retorno = categDAO.atualizar(categoria);
        }

        if (retorno == null) {
            JOptionPane.showMessageDialog(null, "Registro salvo com sucesso!");

            tfddescricao.setText("");
            tfddescricao.requestFocus();

            id = 0;

        } else {
            JOptionPane.showMessageDialog(null, "Problemas ao salvar registro!\n\n"
                    + "Mensagem técnica:\n"
                    + "Erro: " + retorno);
        }
    
        
    }//GEN-LAST:event_btncadastrarcatActionPerformed

    private void tfdtituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdtituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdtituloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgCadastro dialog = new DlgCadastro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncadastrarcat;
    private javax.swing.JComboBox<String> cmbSituacaocat;
    private javax.swing.JComboBox<String> cmbautor;
    private javax.swing.JComboBox<String> cmbcategoria;
    private javax.swing.JComboBox<String> cmbestante;
    private javax.swing.JComboBox<String> cmbidioma;
    private javax.swing.JLabel lblfundo;
    private javax.swing.JLabel lblfundoLivros;
    private javax.swing.JLabel lblregistrar;
    private javax.swing.JPanel pnlautor;
    private javax.swing.JPanel pnlcategoria;
    private javax.swing.JPanel pnlclientes;
    private javax.swing.JPanel pnllivros;
    private javax.swing.JTextField tfddescricao;
    private javax.swing.JTextField tfdtitulo;
    // End of variables declaration//GEN-END:variables
}
