/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import dao.FuncionarioDAO;
import entidade.Funcionario;
import javax.swing.JOptionPane;

/**
 *
 * @author evely
 */
public class DlgEditarPerfil extends javax.swing.JDialog {

    String username;
    String nome;
    String email;
    int id;
    
    public DlgEditarPerfil(java.awt.Frame parent, boolean modal, int id, String username, String nome, String email) {
        super(parent, modal);
        initComponents();
        
        this.username = username;
        this.nome = nome;
        this.email = email;
        this.id = id;
        
        tfdnome.setText(nome);
        tfdemail.setText(email);
        tfdnomeusuario.setText(username);
        
        lblerror.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblerror = new javax.swing.JLabel();
        tfdemail = new javax.swing.JTextField();
        tfdnome = new javax.swing.JTextField();
        tfdnomeusuario = new javax.swing.JTextField();
        btnalterarsenha = new javax.swing.JButton();
        btnpronto = new javax.swing.JButton();
        lblfechar = new javax.swing.JLabel();
        lblfundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblerror.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblerror.setForeground(new java.awt.Color(255, 0, 51));
        lblerror.setText("Algum campo não foi preenchido corretamente.");
        lblerror.setToolTipText("");
        getContentPane().add(lblerror, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 520, -1, -1));

        tfdemail.setBackground(new java.awt.Color(0, 0, 0));
        tfdemail.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        tfdemail.setForeground(new java.awt.Color(255, 255, 255));
        tfdemail.setBorder(null);
        getContentPane().add(tfdemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 377, 320, 30));

        tfdnome.setBackground(new java.awt.Color(0, 0, 0));
        tfdnome.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        tfdnome.setForeground(new java.awt.Color(255, 255, 255));
        tfdnome.setBorder(null);
        getContentPane().add(tfdnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 182, 320, 30));

        tfdnomeusuario.setBackground(new java.awt.Color(0, 0, 0));
        tfdnomeusuario.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        tfdnomeusuario.setForeground(new java.awt.Color(255, 255, 255));
        tfdnomeusuario.setBorder(null);
        getContentPane().add(tfdnomeusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 320, 30));

        btnalterarsenha.setBackground(new java.awt.Color(23, 169, 168));
        btnalterarsenha.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnalterarsenha.setForeground(new java.awt.Color(255, 255, 255));
        btnalterarsenha.setText("Alterar Senha");
        btnalterarsenha.setBorder(null);
        btnalterarsenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnalterarsenhaActionPerformed(evt);
            }
        });
        getContentPane().add(btnalterarsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 150, 40));

        btnpronto.setBackground(new java.awt.Color(23, 169, 168));
        btnpronto.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnpronto.setForeground(new java.awt.Color(255, 255, 255));
        btnpronto.setText("Pronto");
        btnpronto.setBorder(null);
        btnpronto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprontoActionPerformed(evt);
            }
        });
        getContentPane().add(btnpronto, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 150, 40));

        lblfechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblfecharMouseClicked(evt);
            }
        });
        getContentPane().add(lblfechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 30, 30));

        lblfundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/livraria/imagens/editarperfilimg.png"))); // NOI18N
        getContentPane().add(lblfundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblfecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblfecharMouseClicked
        this.dispose();
    }//GEN-LAST:event_lblfecharMouseClicked

    private void btnalterarsenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnalterarsenhaActionPerformed
        DlgAlterarSenha telasenha = new DlgAlterarSenha (null, true, username);
        this.dispose();
        telasenha.setVisible(true);
    }//GEN-LAST:event_btnalterarsenhaActionPerformed

    private void btnprontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprontoActionPerformed
        
        if (tfdnome.getText().trim().isEmpty() || tfdnomeusuario.getText().trim().isEmpty()) {
            lblerror.setVisible(true);
        } else {
        
        FuncionarioDAO dao = new FuncionarioDAO();
        Funcionario funcionario = new Funcionario();
        funcionario = dao.consultarId(id);
        
        funcionario.setNome(tfdnome.getText());
        funcionario.setUsername(tfdnomeusuario.getText());
        funcionario.setEmail(tfdemail.getText());
        
        dao.atualizar(funcionario);
        JOptionPane.showMessageDialog(null, "Perfil editado com sucesso!");
        }
    }//GEN-LAST:event_btnprontoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnalterarsenha;
    private javax.swing.JButton btnpronto;
    private javax.swing.JLabel lblerror;
    private javax.swing.JLabel lblfechar;
    private javax.swing.JLabel lblfundo;
    private javax.swing.JTextField tfdemail;
    private javax.swing.JTextField tfdnome;
    private javax.swing.JTextField tfdnomeusuario;
    // End of variables declaration//GEN-END:variables
}
