/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import apoio.ComboItem;
import apoio.CombosDAO;
import dao.LivroDAO;
import entidade.Livro;
import java.awt.Toolkit;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author evely
 */
public class DlgLivros extends javax.swing.JDialog {
        int id = 0;
        Livro livro = new Livro();
 
        //Categoria categ = new Categoria();
        
    public DlgLivros(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIcon();
        new CombosDAO().popularCombo("categoria", cmbcategoria);
        new CombosDAO().popularCombo("estante", cmbestante);
        new CombosDAO().popularCombo("editora", cmbeditora);
        new CombosDAO().popularCombo("autor", cmbautor);
        lblerror.setVisible(false);
    }
    
    public DlgLivros(java.awt.Frame parent, boolean modal, Livro livro) {
        super(parent, modal);
        initComponents();     
        
        setIcon();
        popularCombos(livro);
        lblerror.setVisible(false);
        
        tfdqtd.setText(Integer.toString(livro.getQuantidade()));
        tfdtitulo.setText(livro.getTitulo());
        
        String custo = priceToString(livro.getValor_custo());
        String venda = priceToString(livro.getValor_venda());
        tfdcusto.setText(custo);
        tfdvenda.setText(venda);
        
        if (livro.getSituacao() == 'a') {
            cmbsituacao.setSelectedIndex(0);
        } else {
            cmbsituacao.setSelectedIndex(1);
        }
        this.livro = livro;
    }
    
    public void setIcon(){
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnllivros = new javax.swing.JPanel();
        din1 = new javax.swing.JLabel();
        din2 = new javax.swing.JLabel();
        tfdvenda = new apoio.JCurrencyField();
        tfdcusto = new apoio.JCurrencyField();
        tfdqtd = new apoio.JNumberField();
        lblerror = new javax.swing.JLabel();
        lblregistrar = new javax.swing.JLabel();
        cmbsituacao = new javax.swing.JComboBox<>();
        cmbeditora = new javax.swing.JComboBox<>();
        cmbestante = new javax.swing.JComboBox<>();
        cmbidioma = new javax.swing.JComboBox<>();
        cmbcategoria = new javax.swing.JComboBox<>();
        cmbautor = new javax.swing.JComboBox<>();
        tfdtitulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Livros");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnllivros.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        din1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        din1.setText("R$");
        pnllivros.add(din1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 328, -1, -1));

        din2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        din2.setText("R$");
        pnllivros.add(din2, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 328, -1, -1));

        tfdvenda.setBorder(null);
        tfdvenda.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfdvenda.setText(",00");
        pnllivros.add(tfdvenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 170, 30));

        tfdcusto.setBorder(null);
        tfdcusto.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfdcusto.setText(",00");
        pnllivros.add(tfdcusto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 180, 30));
        pnllivros.add(tfdqtd, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 547, 60, 30));

        lblerror.setForeground(new java.awt.Color(255, 0, 0));
        lblerror.setText("Certifique-se de que todos os campos foram preenchidos corretamente.");
        pnllivros.add(lblerror, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 660, -1, -1));

        lblregistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblregistrarMouseClicked(evt);
            }
        });
        pnllivros.add(lblregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 580, 210, 60));

        cmbsituacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Inativo" }));
        pnllivros.add(cmbsituacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 210, 30));

        cmbeditora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnllivros.add(cmbeditora, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 210, 30));

        cmbestante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnllivros.add(cmbestante, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 210, 30));

        cmbidioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Português", "Inglês" }));
        pnllivros.add(cmbidioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 210, 30));

        cmbcategoria.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cmbcategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnllivros.add(cmbcategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 210, 30));

        cmbautor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cmbautor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnllivros.add(cmbautor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 210, 30));

        tfdtitulo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfdtitulo.setBorder(null);
        pnllivros.add(tfdtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 153, 440, 36));
        tfdtitulo.getAccessibleContext().setAccessibleName("");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/livraria/imagens/cadastrolivros.png"))); // NOI18N
        pnllivros.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(pnllivros, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblregistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblregistrarMouseClicked
        
        double custo = Double.parseDouble(tfdcusto.getText().replaceAll(",", "."));
        double venda = Double.parseDouble(tfdvenda.getText().replaceAll(",", "."));
        
        if (tfdtitulo.getText().trim().isEmpty() || tfdcusto.getText().trim().isEmpty() || tfdvenda.getText().trim().isEmpty()
                || cmbautor.getSelectedIndex() == 0 || cmbestante.getSelectedIndex() == 0 || cmbeditora.getSelectedIndex() == 0
                || tfdqtd.getText().trim().isEmpty() || cmbcategoria.getSelectedIndex() == 0 || custo >= venda) {
          lblerror.setVisible(true);
          JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos para continuar.");
        } else {
        
        LivroDAO livDAO = new LivroDAO();
        id = livro.getId();
        livro.setTitulo(tfdtitulo.getText());
        livro.setQuantidade(Integer.parseInt(tfdqtd.getText()));
        livro.setValor_custo(custo);
        livro.setValor_venda(venda);
        
        ComboItem ci = (ComboItem) cmbcategoria.getSelectedItem();
        livro.setCategoria_id(ci.getCodigo());
        ComboItem ci2 = (ComboItem) cmbautor.getSelectedItem();
        livro.setAutor_id(ci2.getCodigo());
        ComboItem ci3 = (ComboItem) cmbeditora.getSelectedItem();
        livro.setEditora_id(ci3.getCodigo());
        ComboItem ci4 = (ComboItem) cmbestante.getSelectedItem();
        livro.setEstante_id(ci4.getCodigo());
        
        int idcidioma = cmbidioma.getSelectedIndex();      
        if (idcidioma == 0){
            livro.setIdioma("Português");
        } else {
           livro.setIdioma("Inglês");
        }
        
        
        int idcsit = cmbsituacao.getSelectedIndex();
        if (idcsit == 0) {
            livro.setSituacao('a');
        } else {
            livro.setSituacao('i');
        }

        String retorno = null;
         
        if (id == 0) {
            retorno = livDAO.salvar(livro);
            this.dispose();
        } else {
            retorno = livDAO.atualizar(livro);
            this.dispose();
        }

        if (retorno == null) {
            JOptionPane.showMessageDialog(null, "Registro salvo com sucesso!");
         

            id = 0;

        } else {
            JOptionPane.showMessageDialog(null, "Problemas ao salvar registro!\n\n"
                + "Mensagem técnica:\n"
                + "Erro: " + retorno);
        }
        }
    }//GEN-LAST:event_lblregistrarMouseClicked
     
    public static String priceWithDecimal (Double price) {
    DecimalFormat formatter = new DecimalFormat("###,###,###.00");
    return formatter.format(price);
}

    public static String priceWithoutDecimal (Double price) {
    DecimalFormat formatter = new DecimalFormat("###,###,###.##");
    return formatter.format(price);
}

    public static String priceToString(Double price) {
    String toShow = priceWithoutDecimal(price);
    if (toShow.indexOf(".") > 0) {
        return priceWithDecimal(price);
    } else {
        return priceWithoutDecimal(price);
    }
}

    public void popularCombos(Livro livro){
        new CombosDAO().popularCombo("categoria", cmbcategoria);
        new CombosDAO().popularCombo("estante", cmbestante);
        new CombosDAO().popularCombo("editora", cmbeditora);
        new CombosDAO().popularCombo("autor", cmbautor);
        cmbcategoria.setSelectedIndex(livro.getCategoria_id());
        cmbestante.setSelectedIndex(livro.getEstante_id());
        cmbeditora.setSelectedIndex(livro.getEditora_id());
        cmbautor.setSelectedIndex(livro.getAutor_id());
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgLivros dialog = new DlgLivros(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbautor;
    private javax.swing.JComboBox<String> cmbcategoria;
    private javax.swing.JComboBox<String> cmbeditora;
    private javax.swing.JComboBox<String> cmbestante;
    private javax.swing.JComboBox<String> cmbidioma;
    private javax.swing.JComboBox<String> cmbsituacao;
    private javax.swing.JLabel din1;
    private javax.swing.JLabel din2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblerror;
    private javax.swing.JLabel lblregistrar;
    private javax.swing.JPanel pnllivros;
    private apoio.JCurrencyField tfdcusto;
    private apoio.JNumberField tfdqtd;
    private javax.swing.JTextField tfdtitulo;
    private apoio.JCurrencyField tfdvenda;
    // End of variables declaration//GEN-END:variables
}
