/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import com.toedter.calendar.JDateChooser;
import dao.ClienteDAO;
import dao.VendaDAO;
import entidade.Cliente;
import entidade.Venda;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author evely
 */
public class DlgPagamento extends javax.swing.JDialog {

    Venda vendainfo = new Venda();

    public DlgPagamento(java.awt.Frame parent, boolean modal, Venda venda) {
        super(parent, modal);
        initComponents();
        tfdTroco.setVisible(false);
        lblTroco.setVisible(false);
        chkDinheiro.setSelected(false);
        chkCartao.setSelected(false);
        tfdPagar.setEditable(false);
        tfdnome.setVisible(false);
        lblTotal.setText(Double.toString(venda.getValor_pagamento()));

        vendainfo.setId(venda.getId());
        vendainfo.setFuncionario_id(venda.getFuncionario_id());
        vendainfo.setValor_pagamento(venda.getValor_pagamento());
    }

    String formapagamento = "";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfdTroco = new javax.swing.JTextField();
        btnconferir = new javax.swing.JButton();
        btnfechar = new javax.swing.JLabel();
        btncancelar = new javax.swing.JButton();
        btnfinalizar = new javax.swing.JButton();
        chkCartao = new javax.swing.JCheckBox();
        chkDinheiro = new javax.swing.JCheckBox();
        tfdCpf = new apoio.JCpfField();
        tfdnome = new javax.swing.JTextField();
        lblcpf = new javax.swing.JLabel();
        lblTroco = new javax.swing.JLabel();
        lblPagar = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        tfdPagar = new apoio.JCurrencyField();
        btnBuscarCliente = new javax.swing.JButton();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bookzone: Pagamento");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfdTroco.setBackground(new java.awt.Color(0, 0, 0));
        tfdTroco.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        tfdTroco.setForeground(new java.awt.Color(255, 255, 255));
        tfdTroco.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfdTroco.setToolTipText("");
        tfdTroco.setBorder(null);
        getContentPane().add(tfdTroco, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 180, 30));

        btnconferir.setText("jButton1");
        btnconferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconferirActionPerformed(evt);
            }
        });
        getContentPane().add(btnconferir, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 30, 30));

        btnfechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnfecharMouseClicked(evt);
            }
        });
        getContentPane().add(btnfechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 30, 30));

        btncancelar.setBackground(new java.awt.Color(255, 0, 0));
        btncancelar.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        btncancelar.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar.setText("Cancelar");
        btncancelar.setBorder(null);
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 573, 140, 30));

        btnfinalizar.setBackground(new java.awt.Color(2, 166, 166));
        btnfinalizar.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        btnfinalizar.setForeground(new java.awt.Color(255, 255, 255));
        btnfinalizar.setText("Finalizar venda");
        btnfinalizar.setBorder(null);
        btnfinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfinalizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnfinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 573, 140, 30));

        chkCartao.setBackground(new java.awt.Color(32, 32, 32));
        chkCartao.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        chkCartao.setForeground(new java.awt.Color(255, 255, 255));
        chkCartao.setText("    Cartão");
        chkCartao.setToolTipText("");
        chkCartao.setFocusPainted(false);
        chkCartao.setOpaque(false);
        chkCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCartaoActionPerformed(evt);
            }
        });
        getContentPane().add(chkCartao, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));

        chkDinheiro.setBackground(new java.awt.Color(32, 32, 32));
        chkDinheiro.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        chkDinheiro.setForeground(new java.awt.Color(255, 255, 255));
        chkDinheiro.setText("    Dinheiro");
        chkDinheiro.setToolTipText("");
        chkDinheiro.setFocusPainted(false);
        chkDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDinheiroActionPerformed(evt);
            }
        });
        getContentPane().add(chkDinheiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        tfdCpf.setBackground(new java.awt.Color(0, 0, 0));
        tfdCpf.setBorder(null);
        tfdCpf.setForeground(new java.awt.Color(255, 255, 255));
        tfdCpf.setToolTipText("");
        getContentPane().add(tfdCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 180, 30));

        tfdnome.setEditable(false);
        tfdnome.setBackground(new java.awt.Color(0, 0, 0));
        tfdnome.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        tfdnome.setForeground(new java.awt.Color(255, 255, 255));
        tfdnome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfdnome.setBorder(null);
        getContentPane().add(tfdnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 280, 30));

        lblcpf.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblcpf.setForeground(new java.awt.Color(255, 255, 255));
        lblcpf.setText("CPF:");
        getContentPane().add(lblcpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, -1, -1));

        lblTroco.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblTroco.setForeground(new java.awt.Color(255, 255, 255));
        lblTroco.setText("Troco:");
        getContentPane().add(lblTroco, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));

        lblPagar.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblPagar.setForeground(new java.awt.Color(255, 255, 255));
        lblPagar.setText("Pagar:");
        getContentPane().add(lblPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        lblTotal.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 140, 40));

        tfdPagar.setBackground(new java.awt.Color(0, 0, 0));
        tfdPagar.setBorder(null);
        tfdPagar.setForeground(new java.awt.Color(255, 255, 255));
        tfdPagar.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfdPagar.setToolTipText("");
        getContentPane().add(tfdPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 180, 30));

        btnBuscarCliente.setBackground(new java.awt.Color(2, 166, 166));
        btnBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/livraria/imagens/pesquisa.png"))); // NOI18N
        btnBuscarCliente.setBorder(null);
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, 30, 30));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/livraria/imagens/formapagamento.png"))); // NOI18N
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chkDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDinheiroActionPerformed
        if (chkDinheiro.isSelected()) {
            chkCartao.setSelected(false);
            tfdPagar.setEditable(true);
            lblTroco.setVisible(false);
            formapagamento = "Dinheiro";
        }
    }//GEN-LAST:event_chkDinheiroActionPerformed

    private void chkCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCartaoActionPerformed
        chkDinheiro.setSelected(false);
        tfdTroco.setVisible(false);
        tfdPagar.setEditable(true);
        lblTroco.setVisible(false);
        formapagamento = "Cartão";
    }//GEN-LAST:event_chkCartaoActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        ClienteDAO dao = new ClienteDAO();
        Cliente cliente = new Cliente();
        cliente = dao.consultarCpf(tfdCpf.getText());
        if (cliente != null) {
            tfdnome.setVisible(true);
            tfdnome.setText(cliente.getNome());
            vendainfo.setCliente_id(cliente.getId());
        } else {
            tfdnome.setText("Cliente não encontrado");
        }
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnfecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnfecharMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnfecharMouseClicked

    private void btnconferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconferirActionPerformed
        double valorPagar = Double.valueOf(tfdPagar.getText().replaceAll(",", ".")).doubleValue();
        double total = Double.valueOf(lblTotal.getText()).doubleValue();
        double troco = 0;

        if (valorPagar == total) {
            lblTroco.setVisible(false);
            tfdTroco.setVisible(false);

        } else if (valorPagar > total && chkDinheiro.isSelected()) {
            tfdTroco.setVisible(true);
            lblTroco.setVisible(true);
            troco = valorPagar - total;
            tfdTroco.setText(Double.toString(troco));
        }
    }//GEN-LAST:event_btnconferirActionPerformed

    private void btnfinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfinalizarActionPerformed

        if (!chkDinheiro.isSelected() && !chkCartao.isSelected()) {
            JOptionPane.showMessageDialog(rootPane,
                    "Você precisa selecionar uma forma de pagamento!",
                    "Atencão",
                    JOptionPane.ERROR_MESSAGE);
        } else if (tfdPagar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane,
                    "Você precisa informar o valor a ser pago!",
                    "Atencão",
                    JOptionPane.ERROR_MESSAGE);
        } else if (tfdnome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane,
                    "O cpf do cliente deve ser informado!",
                    "Atencão",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            VendaDAO dao = new VendaDAO();
            vendainfo.setForma_pagamento(formapagamento);
            java.util.Date data = new Date();
            vendainfo.setData_venda(data);
        }


    }//GEN-LAST:event_btnfinalizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnconferir;
    private javax.swing.JLabel btnfechar;
    private javax.swing.JButton btnfinalizar;
    private javax.swing.JCheckBox chkCartao;
    private javax.swing.JCheckBox chkDinheiro;
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel lblPagar;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTroco;
    private javax.swing.JLabel lblcpf;
    private apoio.JCpfField tfdCpf;
    private apoio.JCurrencyField tfdPagar;
    private javax.swing.JTextField tfdTroco;
    private javax.swing.JTextField tfdnome;
    // End of variables declaration//GEN-END:variables
}
