/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import dao.LivroDAO;
import entidade.Funcionario;
import entidade.Livro;
import java.awt.Color;
import java.awt.Font;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author evely
 */
public class MenuGUI extends javax.swing.JFrame {

    public MenuGUI(Funcionario funcionario) {
        initComponents();  
        
        setIcon();
        configurarBotoes();
        configurarTblLivros();
        // configs dos paineis
        pnlhome.setVisible(true);
        pnlcadastro.setVisible(false);
        lblfuncionario.setText(funcionario.getNome());
        new LivroDAO().popularTabela(tbllivros,"");
                      
    }
    
    public void configurarTblLivros(){
        tbllivros.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 15));
        tbllivros.getTableHeader().setOpaque(false);
        tbllivros.getTableHeader().setBackground(new Color (31,118,138));
    }
    
    public void configurarBotoes() {
        btnhome.setBackground(new Color(0,102,102));
        btnhome.setFocusPainted(false);
        btncadastro.setFocusPainted(false);
        btnprodutos.setFocusPainted(false);
        btnvendas.setFocusPainted(false);      
        btnupdate.setFocusPainted(false);
        btncadastro.setBackground(new Color(26,30,31));
        btnvendas.setBackground(new Color(26,30,31));
        btnprodutos.setBackground(new Color(26,30,31));
    }
    
    public void setIcon(){
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlfundo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        pnlmenu = new javax.swing.JPanel();
        btnhome = new javax.swing.JButton();
        btncadastro = new javax.swing.JButton();
        btnvendas = new javax.swing.JButton();
        btnprodutos = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        iconuser = new javax.swing.JLabel();
        lblfuncionario = new javax.swing.JLabel();
        pnlhome = new javax.swing.JPanel();
        pnlcadastro = new javax.swing.JPanel();
        jtblcadastro = new javax.swing.JTabbedPane();
        pnlCliente = new javax.swing.JPanel();
        pnllivros = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbllivros = new javax.swing.JTable();
        tfdbusca = new javax.swing.JTextField();
        btnpesquisa = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        pnlAutor = new javax.swing.JPanel();
        pnlvendas = new javax.swing.JPanel();
        jSlider1 = new javax.swing.JSlider();
        pnlprodutos = new javax.swing.JPanel();
        jScrollBar1 = new javax.swing.JScrollBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlfundo.setBackground(new java.awt.Color(230, 228, 228));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlmenu.setBackground(new java.awt.Color(26, 30, 31));

        btnhome.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnhome.setForeground(new java.awt.Color(255, 255, 255));
        btnhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/livraria/imagens/botaohome.png"))); // NOI18N
        btnhome.setToolTipText("Home");
        btnhome.setBorder(null);
        btnhome.setHideActionText(true);
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });

        btncadastro.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btncadastro.setForeground(new java.awt.Color(255, 255, 255));
        btncadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/livraria/imagens/botaocadastro.png"))); // NOI18N
        btncadastro.setToolTipText("Cadastro");
        btncadastro.setBorder(null);
        btncadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncadastroActionPerformed(evt);
            }
        });

        btnvendas.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnvendas.setForeground(new java.awt.Color(255, 255, 255));
        btnvendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/livraria/imagens/botaovendas.png"))); // NOI18N
        btnvendas.setToolTipText("Vendas");
        btnvendas.setBorder(null);
        btnvendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvendasActionPerformed(evt);
            }
        });

        btnprodutos.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnprodutos.setForeground(new java.awt.Color(255, 255, 255));
        btnprodutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/livraria/imagens/botaoprod.png"))); // NOI18N
        btnprodutos.setToolTipText("Produtos");
        btnprodutos.setBorder(null);
        btnprodutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprodutosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlmenuLayout = new javax.swing.GroupLayout(pnlmenu);
        pnlmenu.setLayout(pnlmenuLayout);
        pnlmenuLayout.setHorizontalGroup(
            pnlmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btncadastro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
            .addComponent(btnhome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnvendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnprodutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlmenuLayout.setVerticalGroup(
            pnlmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlmenuLayout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(btnhome, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btncadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnvendas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnprodutos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(282, Short.MAX_VALUE))
        );

        pnlmenuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btncadastro, btnhome, btnprodutos, btnvendas});

        jPanel1.add(pnlmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 770));

        jPanel4.setBackground(new java.awt.Color(23, 169, 168));

        iconuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/livraria/imagens/userlog.png"))); // NOI18N

        lblfuncionario.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblfuncionario.setForeground(new java.awt.Color(255, 255, 255));
        lblfuncionario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblfuncionario.setText("UserName   ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(1061, Short.MAX_VALUE)
                .addComponent(lblfuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(iconuser)
                .addGap(27, 27, 27))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblfuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(iconuser)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 1250, 80));

        pnlhome.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlhomeLayout = new javax.swing.GroupLayout(pnlhome);
        pnlhome.setLayout(pnlhomeLayout);
        pnlhomeLayout.setHorizontalGroup(
            pnlhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1250, Short.MAX_VALUE)
        );
        pnlhomeLayout.setVerticalGroup(
            pnlhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );

        jPanel1.add(pnlhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 1250, 690));

        pnlcadastro.setBackground(new java.awt.Color(204, 204, 204));

        jtblcadastro.setBackground(new java.awt.Color(204, 204, 204));
        jtblcadastro.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N

        javax.swing.GroupLayout pnlClienteLayout = new javax.swing.GroupLayout(pnlCliente);
        pnlCliente.setLayout(pnlClienteLayout);
        pnlClienteLayout.setHorizontalGroup(
            pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1245, Short.MAX_VALUE)
        );
        pnlClienteLayout.setVerticalGroup(
            pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 655, Short.MAX_VALUE)
        );

        jtblcadastro.addTab("Cliente", pnlCliente);

        pnllivros.setBackground(new java.awt.Color(255, 255, 255));

        tbllivros.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tbllivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código", "Descrição", "Situação"
            }
        ));
        tbllivros.setGridColor(new java.awt.Color(204, 204, 204));
        tbllivros.setRowHeight(35);
        tbllivros.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tbllivros.setShowVerticalLines(false);
        tbllivros.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbllivros);

        tfdbusca.setBackground(new java.awt.Color(242, 243, 245));
        tfdbusca.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        tfdbusca.setForeground(new java.awt.Color(151, 156, 164));
        tfdbusca.setText("Pesquisar por livros...");
        tfdbusca.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tfdbusca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfdbuscaMouseClicked(evt);
            }
        });

        btnpesquisa.setBackground(new java.awt.Color(18, 151, 160));
        btnpesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/livraria/imagens/pesquisa.png"))); // NOI18N
        btnpesquisa.setToolTipText("Pesquisar");
        btnpesquisa.setFocusPainted(false);
        btnpesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesquisaActionPerformed(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(18, 151, 160));
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/livraria/imagens/lixeira.png"))); // NOI18N
        btnExcluir.setToolTipText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(18, 151, 160));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/livraria/imagens/edit.png"))); // NOI18N
        btnEditar.setToolTipText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnAdicionar.setBackground(new java.awt.Color(18, 151, 160));
        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/livraria/imagens/add.png"))); // NOI18N
        btnAdicionar.setToolTipText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnupdate.setBackground(new java.awt.Color(18, 151, 160));
        btnupdate.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnupdate.setForeground(new java.awt.Color(255, 255, 255));
        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/livraria/imagens/refresh.png"))); // NOI18N
        btnupdate.setText("Atualizar lista");
        btnupdate.setToolTipText("");
        btnupdate.setBorder(null);
        btnupdate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnupdate.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnllivrosLayout = new javax.swing.GroupLayout(pnllivros);
        pnllivros.setLayout(pnllivrosLayout);
        pnllivrosLayout.setHorizontalGroup(
            pnllivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnllivrosLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(pnllivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1057, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnllivrosLayout.createSequentialGroup()
                        .addComponent(tfdbusca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnllivrosLayout.createSequentialGroup()
                        .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        pnllivrosLayout.setVerticalGroup(
            pnllivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnllivrosLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(pnllivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfdbusca, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnllivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jtblcadastro.addTab("Livros", pnllivros);

        javax.swing.GroupLayout pnlAutorLayout = new javax.swing.GroupLayout(pnlAutor);
        pnlAutor.setLayout(pnlAutorLayout);
        pnlAutorLayout.setHorizontalGroup(
            pnlAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1245, Short.MAX_VALUE)
        );
        pnlAutorLayout.setVerticalGroup(
            pnlAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 655, Short.MAX_VALUE)
        );

        jtblcadastro.addTab("Autor", pnlAutor);

        javax.swing.GroupLayout pnlcadastroLayout = new javax.swing.GroupLayout(pnlcadastro);
        pnlcadastro.setLayout(pnlcadastroLayout);
        pnlcadastroLayout.setHorizontalGroup(
            pnlcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtblcadastro)
        );
        pnlcadastroLayout.setVerticalGroup(
            pnlcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtblcadastro)
        );

        jPanel1.add(pnlcadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 1250, 690));

        pnlvendas.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout pnlvendasLayout = new javax.swing.GroupLayout(pnlvendas);
        pnlvendas.setLayout(pnlvendasLayout);
        pnlvendasLayout.setHorizontalGroup(
            pnlvendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlvendasLayout.createSequentialGroup()
                .addGap(367, 367, 367)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(683, Short.MAX_VALUE))
        );
        pnlvendasLayout.setVerticalGroup(
            pnlvendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlvendasLayout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(456, Short.MAX_VALUE))
        );

        jPanel1.add(pnlvendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 1250, 690));

        pnlprodutos.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout pnlprodutosLayout = new javax.swing.GroupLayout(pnlprodutos);
        pnlprodutos.setLayout(pnlprodutosLayout);
        pnlprodutosLayout.setHorizontalGroup(
            pnlprodutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlprodutosLayout.createSequentialGroup()
                .addContainerGap(769, Short.MAX_VALUE)
                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(464, 464, 464))
        );
        pnlprodutosLayout.setVerticalGroup(
            pnlprodutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlprodutosLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(476, Short.MAX_VALUE))
        );

        jPanel1.add(pnlprodutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 1250, 690));

        javax.swing.GroupLayout pnlfundoLayout = new javax.swing.GroupLayout(pnlfundo);
        pnlfundo.setLayout(pnlfundoLayout);
        pnlfundoLayout.setHorizontalGroup(
            pnlfundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlfundoLayout.setVerticalGroup(
            pnlfundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlfundo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlfundo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
        pnlhome.setVisible(true);
        btnhome.setBackground(new Color (0,102,102));
        btncadastro.setBackground(new Color (26,30,31));
        btnvendas.setBackground(new Color (26,30,31));
        btnprodutos.setBackground(new Color (26,30,31));
    }//GEN-LAST:event_btnhomeActionPerformed

    private void btncadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncadastroActionPerformed
        pnlcadastro.setVisible(true);
        pnlhome.setVisible(false);
        btnhome.setBackground(new Color (26,30,31));
        btncadastro.setBackground(new Color (0,102,102));
        btnvendas.setBackground(new Color (26,30,31));
        btnprodutos.setBackground(new Color (26,30,31));
    }//GEN-LAST:event_btncadastroActionPerformed

    private void btnvendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvendasActionPerformed
        pnlvendas.setVisible(true);
        pnlhome.setVisible(false);
        pnlcadastro.setVisible(false);
        btnhome.setBackground(new Color (26,30,31));
        btncadastro.setBackground(new Color (26,30,31));
        btnvendas.setBackground(new Color (0,102,102));
        btnprodutos.setBackground(new Color (26,30,31));
    }//GEN-LAST:event_btnvendasActionPerformed

    private void btnprodutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprodutosActionPerformed
        pnlprodutos.setVisible(true);
        pnlhome.setVisible(false);
        pnlcadastro.setVisible(false);
        pnlvendas.setVisible(false);
        btnhome.setBackground(new Color (27,33,45));
        btncadastro.setBackground(new Color (27,33,45));
        btnvendas.setBackground(new Color (27,33,45));
        btnprodutos.setBackground(new Color (0,102,102));
    }//GEN-LAST:event_btnprodutosActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        new LivroDAO().popularTabela(tbllivros,"");      
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        DlgCadastro tela = new DlgCadastro(null, true);
        tela.setVisible(true);
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

        String idString = String.valueOf(tbllivros.getValueAt(tbllivros.getSelectedRow(), 0));
        int id = Integer.parseInt(idString);
        Livro livro = new LivroDAO().consultarId(id);

        DlgCadastro tela = new DlgCadastro(null, true, livro);
        tela.setVisible(true);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        Object[] options = { "Inativar", "Excluir" };
        int opcao = JOptionPane.showOptionDialog(null, "Escolha a opção desejada/n", "Excluir", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);

        System.out.println("Opção = " + opcao);
        String idString = String.valueOf(tbllivros.getValueAt(tbllivros.getSelectedRow(), 0));
        int id = Integer.parseInt(idString);

        if (opcao == 0){

            String retorno = new LivroDAO().inativar(id);
            if (retorno == null) {
                JOptionPane.showMessageDialog(null, "Registro inativado com sucesso!");
                new LivroDAO().popularTabela(tbllivros, "");
            } else {
                JOptionPane.showMessageDialog(null, "Ops, problemas ao inativar registro.");
            }
        }

        if (opcao == 1) {
            String retorno = new LivroDAO().excluir(id);
            if (retorno == null) {
                JOptionPane.showMessageDialog(null, "Registro excluído com sucesso!");
                new LivroDAO().popularTabela(tbllivros, "");
            } else {
                JOptionPane.showMessageDialog(null, "Ops, problemas ao excluir registro.");
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnpesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesquisaActionPerformed
        new LivroDAO().popularTabela(tbllivros, tfdbusca.getText());
    }//GEN-LAST:event_btnpesquisaActionPerformed

    private void tfdbuscaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfdbuscaMouseClicked
        tfdbusca.setText("");
        tfdbusca.setForeground(Color.BLACK);
    }//GEN-LAST:event_tfdbuscaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btncadastro;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnpesquisa;
    private javax.swing.JButton btnprodutos;
    private javax.swing.JButton btnupdate;
    private javax.swing.JButton btnvendas;
    private javax.swing.JLabel iconuser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTabbedPane jtblcadastro;
    private javax.swing.JLabel lblfuncionario;
    private javax.swing.JPanel pnlAutor;
    private javax.swing.JPanel pnlCliente;
    private javax.swing.JPanel pnlcadastro;
    private javax.swing.JPanel pnlfundo;
    private javax.swing.JPanel pnlhome;
    private javax.swing.JPanel pnllivros;
    private javax.swing.JPanel pnlmenu;
    private javax.swing.JPanel pnlprodutos;
    private javax.swing.JPanel pnlvendas;
    private javax.swing.JTable tbllivros;
    private javax.swing.JTextField tfdbusca;
    // End of variables declaration//GEN-END:variables

   

  

}
